In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import operator
import sklearn
import sklearn.model_selection
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

import re
import nltk

In [2]:
import importlib
import src.models as model
importlib.reload(model)
import src.utils as util
importlib.reload(util);

In [4]:
#global data
training_set = pd.read_csv("data/covid_training.tsv", sep="\t")
test_set = pd.read_csv("data/test_set04.tsv", sep="\t", header=None)
preX = training_set.values[:,1]
prey = training_set.values[:,2]
X = np.array(preX).reshape(-1, 1)
categories = list(set(prey))
#categories.reverse() #fix random seed of set uncertain index
y = np.array([categories.index(ele) for ele in prey]).reshape(-1,1)

X_test = test_set.values[:,1].reshape(-1, 1)
y_test = np.array([categories.index(ele) for ele in test_set.values[:,2]]).reshape(-1,1)
X_train, X_val, y_train, y_val = sklearn.model_selection.train_test_split(X, y, train_size=0.9, random_state=0)
print(X.shape)
print(X_test.shape)

(399, 1)
(10, 1)


In [5]:
#data format
pd.DataFrame(data=np.column_stack([X_test,y_test]),columns=["Training Examples","Training Labels"]).head()
pd.DataFrame(data=np.column_stack([X,y]),columns=["Training Examples","Training Labels"]).head()

Training Examples Training Labels
0  For the average American the best way to tell ...               0
1                           this is fucking bullshit               0
2  Can y’all please just follow the government’s ...               0
3  No offense but the corona virus disappearing b...               0
4  This is the face of someone who just spent 9 h...               1

In [6]:
#training orignal model
nb_bow1 = model.NB_BOW(np.unique(y)) #instantiate a NB class object
print ("---------------- Training In Progress --------------------")
nb_bow1.trainModel(X, y) #start tarining by calling the train function
print ('----------------- Training Completed ---------------------')

---------------- Training In Progress --------------------
1381
2655
1381
2655
----------------- Training Completed ---------------------


In [7]:
#training filter model
nb_bow2 = model.NB_BOW(np.unique(y), True) #instantiate a NB class object
print ("---------------- Training In Progress --------------------")
nb_bow2.trainModel(X, y) #start tarining by calling the train function
print ('----------------- Training Completed ---------------------')

---------------- Training In Progress --------------------
1244
2345
435
865
----------------- Training Completed ---------------------


In [8]:
#testing
util.displayResult(nb_bow1, X_test, y_test)

----------------- Result ---------------------
Test Set Size:      10
Test Set Accuracy:  80.0 %
[0 0 1 1 0 1 1 1 1 1]
[1 0 1 1 0 1 1 0 1 1]


In [9]:
#process
util.processData([nb_bow1, nb_bow2], X_test, y_test, test_set)

----------------- Result ---------------------
Test Set Size:      10
Test Set Accuracy:  80.0 %
[0 0 1 1 0 1 1 1 1 1]
[1 0 1 1 0 1 1 0 1 1]
Trace file produced: 'result/trace_NB-BOW-OV.txt '
Evaluation file produced: 'result/eval_NB-BOW-OV.txt '
TEST: Precision: 0.8571	Recall: 0.8571	F1: 0.8571
----------------- Result ---------------------
Test Set Size:      10
Test Set Accuracy:  80.0 %
[0 0 1 1 0 1 1 1 1 1]
[1 0 1 1 0 1 1 0 1 1]
Trace file produced: 'result/trace_NB-BOW-FV.txt'
Evaluation file produced: 'result/eval_NB-BOW-FV.txt'
TEST: Precision: 0.8571	Recall: 0.8571	F1: 0.8571
