In [11]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn
import sklearn.preprocessing         # For scale function
import sklearn.metrics as metrics    # For for label size

In [12]:
#global data
import importlib
import xpuzzle
importlib.reload(xpuzzle)
import node
importlib.reload(node)
import search
importlib.reload(search)
inputData = np.array([])
goalState=np.array([[1,2,3,4], [5,6,7,0]])

In [16]:
#i/o
def noSolution(name, index, data):
    file = open(f"{index}_" + name + '_solution.txt', 'w')
    file.write(data[0])
    file.close()

    file = open(f"{index}_" + name + '_search.txt', 'w')
    file.write(data[1])
    file.close()
    # file.write("\ncost: " + str(moves))
    # file.write("\nrunning_time: " + format(time, '.8f'))


def exportData(name, index, data):
    cost = 0
    file = open(f"{index}_" + name + '_solution.txt', 'w')
    for ele in data[0].solution:
        file.write(ele)
    file.close()

    file = open(f"{index}_" + name + '_search.txt', 'w')
    for ele in data[1]:
        file.write(ele)
    file.close()

def importData(file_name):
    data = []
    file = open(file_name, 'r')
    for line in file:
        data.append([int(x) for x in line.split(" ")])
    data = np.array(data)
    board_len = len(data[0])
    board_side = int(board_len ** 0.5)
    return data

inputData = importData('samplePuzzles.txt')
print(inputData)

[[3 0 1 4 2 6 5 1]
 [6 3 4 7 1 2 5 0]
 [1 0 3 6 5 2 7 4]
 [0 3 5 1 7 2 4 6]
 [1 3 5 7 0 4 6 2]]


In [28]:
#inputData[0] no solution
t=xpuzzle.XPuzzle(2, 4, inputData[3]) 
t.printPuzzle()

s=search.Search(t)


0 3 5 1 
7 2 4 6 



In [26]:
print("A*")
p  = s.aStar(0)
print(p[0])

if isinstance(p[0], node.Node):
    exportData("astar", 0, p)
else:
    noSolution("astar", 0, p)


A*
no solution


In [33]:
print("GBFS")
p = s.greedyBFS(1)
print(p[0])

if isinstance(p[0], node.Node):
    exportData("gbfs", 0, p)
else:
    noSolution("gbfs", 0, p)

print("\nMoves")
move = str(p[0])
t.parseMoveSequence(move)


GBFS
ZCRRR

Moves
1 3 5 0 
7 2 4 6 

1 3 5 7 
0 2 4 6 

1 3 5 7 
2 0 4 6 

1 3 5 7 
2 4 0 6 

1 3 5 7 
2 4 6 0 

