In [39]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn
import sklearn.preprocessing         # For scale function
import sklearn.metrics as metrics    # For for label size

In [42]:
#global data
import importlib
import xpuzzle
importlib.reload(xpuzzle)
import node
importlib.reload(node)
import search
importlib.reload(search)
inputData = np.array([])
goalState=np.array([[1,2,3,4], [5,6,7,0]])

In [43]:
#i/o
def exportData(name, index, data):

    moves = 1
    file = open(f"{index}_" + name + '_solution.txt', 'w')
    file.write(data[0])
    file.close()
    file = open(f"{index}_" + name + '_search.txt', 'w')
    file.write(data[1])
    file.write("\ncost: " + str(moves))
    #file.write("\nrunning_time: " + format(time, '.8f'))
    file.close()


def importData(file_name):

    data = []
    file = open(file_name, 'r')
    for line in file:
        data.append([int(x) for x in line.split(" ")])

    data = np.array(data)
    board_len = len(data[0])
    board_side = int(board_len ** 0.5)
    return data

inputData = importData('samplePuzzles.txt')
print(inputData)

[[3 0 1 4 2 6 5 7]
 [6 3 4 7 1 2 5 0]
 [1 0 3 6 5 2 7 4]
 [0 3 5 1 7 2 4 6]
 [1 3 5 6 2 0 7 1]]


In [44]:
t=xpuzzle.XPuzzle(2, 4, inputData[3]) #inputData[0] no solution
t.doMove("C")
t.printPuzzle()

s=search.Search(t)

# print("DFS")
# p = s.bestFirst()

# if isinstance(p, node.Node):
#     p.state.printPuzzle()
# else:
#     exportData("dfs", 0, p)

# print("Moves")
# move = p.record()
# t.parseMoveSequence(move)

print("A*")
p = s.aStar(1)
p.state.printPuzzle()


6 3 5 1 
7 2 4 0 

A*
1 3 5 7 
2 4 6 0 

