In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn
import sklearn.preprocessing         # For scale function
import sklearn.metrics as metrics    # For for label size
from copy import deepcopy

In [77]:
#global data
import importlib
import xpuzzle
importlib.reload(xpuzzle)
import node
importlib.reload(node)
import search
importlib.reload(search)
inputData = np.array([])
goalState=np.array([[1,2,3,4], [5,6,7,0]])

In [78]:
#i/o
def exportData(name, index, data):
    cost = 0
    file = open(f"{index}_" + name + '_solution.txt', 'w')
    for ele in data[0].solution:
        file.write(ele)
    file.close()

    file = open(f"{index}_" + name + '_search.txt', 'w')
    for ele in data[1]:
        file.write(ele)
    file.close()
    # file.write("\ncost: " + str(moves))
    # file.write("\nrunning_time: " + format(time, '.8f'))


def importData(file_name):
    data = []
    file = open(file_name, 'r')
    for line in file:
        data.append([int(x) for x in line.split(" ")])
    data = np.array(data)
    board_len = len(data[0])
    board_side = int(board_len ** 0.5)
    return data

inputData = importData('samplePuzzles.txt')
print(inputData)

[[3 0 1 4 2 6 5 7]
 [6 3 4 7 1 2 5 0]
 [1 0 3 6 5 2 7 4]
 [0 3 5 1 7 2 4 6]
 [1 3 5 7 0 4 6 2]]


In [81]:
t=xpuzzle.XPuzzle(2, 4, inputData[3]) #inputData[0] no solution
t.printPuzzle()

s=search.Search(t)

# print("DFS")
# p = s.bestFirst()
# p.state.printPuzzle()
# print(p)

# if isinstance(p, node.Node):
#     p[0].state.printPuzzle()
# else:
#     exportData("dfs", 0, p)

# print("Moves")
# move = str(p)
# t.parseMoveSequence(move)

print("A*")
p  = s.greedyBFS(0)
p[0].getSolution(deepcopy(t))
print(p[0])
if isinstance(p, node.Node):
    exportData("gbfs", 0, p)
else:
    exportData("gbfs", 0, p)


0 3 5 1 
7 2 4 6 

A*
ZCRRR
