In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn
import sklearn.preprocessing         # For scale function
import sklearn.metrics as metrics    # For for label size

In [2]:
#global data
import importlib
import xpuzzle
importlib.reload(xpuzzle)
import search
importlib.reload(search)
inputData = np.array([])
goalState=np.array([[1,2,3,4], [5,6,7,0]])

In [3]:
#i/o
def exportData(frontier, time):

    moves = 1
    file = open('output.txt', 'w')
    file.write("path_to_goal: " + str(moves))
    file.write("\ncost_of_path: " + str(len(moves)))
    file.write("\nnodes_expanded: " + str(nodes_expanded))
    file.write("\nfringe_size: " + str(len(frontier)))
    file.write("\nmax_fringe_size: " + str(max_frontier_size))
    file.write("\nsearch_depth: " + str(goal_node.depth))
    file.write("\nmax_search_depth: " + str(max_search_depth))
    file.write("\nrunning_time: " + format(time, '.8f'))
    file.close()


def importData(file_name):

    data = []
    file = open(file_name, 'r')
    for line in file:
        data.append([int(x) for x in line.split(" ")])

    data = np.array(data)
    board_len = len(data[0])
    board_side = int(board_len ** 0.5)
    return data

inputData = importData('samplePuzzles.txt')
print(inputData)

[[3 0 1 4 2 6 5 7]
 [6 3 4 7 1 2 5 0]
 [1 0 3 6 5 2 7 4]
 [0 3 5 1 7 2 4 6]
 [1 3 5 6 2 0 7 4]]


In [5]:
t=xpuzzle.XPuzzle(2, 4, inputData[3]) #inputData[0] no solution
t.doMove("C")
t.printPuzzle()

s=search.Search(t)
p = s.bestFirst()
p.state.printPuzzle()
p = s.aStar(1)
p.state.printPuzzle()

6 3 5 1 
7 2 4 0 

1 3 5 7 
2 4 6 0 

1 3 5 7 
2 4 6 0 

